min-required-players: 2
max-required-players: 4
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 8.5
  y: -61.5
  z: 8.5
  yaw: 180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: -16.5
    y: 61
    z: -29.5
    yaw: 180
    pitch: 0
  1:
    world: 'world'
    x: 31
    y: 61
    z: -29.5
    yaw: 180
    pitch: 0