name: treasure-battle
version: '${project.version}'
main: me.lutto.treasurebattle.TreasureBattle
api-version: '1.20'
commands:
  arena:
    description: List, Join, Leave Arena's with this command!
    aliases:
      - a
  giveitem:
    description: Get all custom items/blocks using this command!
    aliases:
      - gi